"""Type stubs for the ``volas_rs`` compiled (PyO3) extension module.

Hand-written and kept faithful to the Rust API by ``mypy.stubtest`` in CI. This file
is **static-analysis only** — Python never imports or reads it at runtime, so it has
zero effect on execution speed.

Conventions matching the PyO3 runtime: every class is ``@final`` (pyo3 classes are not
subclassable); constructors are ``__new__``; dunders are positional-only (``/``).
"""

from __future__ import annotations

import datetime
import os
from collections.abc import Iterator
from typing import Any, ClassVar, TypeAlias, final, overload

import numpy as np
import numpy.typing as npt

__all__ = [
    "DataFrame",
    "DatetimeAccessor",
    "_directive_commands",
    "_dtypes",
    "Rolling",
    "Expanding",
    "Ewm",
    "RollingFrame",
    "ExpandingFrame",
    "EwmFrame",
    "DataFrameAt",
    "DataFrameILoc",
    "DataFrameIat",
    "DataFrameLoc",
    "DirectiveError",
    "DirectiveSyntaxError",
    "DirectiveValueError",
    "NA",
    "NAType",
    "Row",
    "Series",
    "SeriesILoc",
    "SeriesLoc",
    "TimeFrame",
    "Timestamp",
    "directive_lookback",
    "directive_stringify",
    "read_csv",
    "to_datetime",
]

# A single cell read out of a Series / Row / cell-accessor. The concrete type depends
# on the column dtype (float / int / bool / string / datetime), and a missing int/bool
# cell is `volas.NA`, so the honest static type is their union.
_Scalar: TypeAlias = "float | int | bool | str | Timestamp | NAType"
# Anything accepted as a boolean row-mask on a frame.
_BoolMask: TypeAlias = "Series | npt.NDArray[np.bool_] | list[bool]"

# The singleton missing-value marker, `volas.NA`. A pure user-facing symbol: an
# int/bool column stores missing as a validity bit, a float column as NaN.
@final
class NAType:
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...

NA: NAType

# --- exceptions -------------------------------------------------------------

class DirectiveError(Exception):
    """Base class for directive parse / evaluation failures."""

class DirectiveSyntaxError(DirectiveError):
    """A directive string could not be parsed."""

class DirectiveValueError(DirectiveError):
    """A directive parsed but could not be evaluated against the frame."""

# --- Timestamp --------------------------------------------------------------

@final
class Timestamp:
    def __new__(cls, value: Any, tz: Any | None = ...) -> Timestamp: ...
    @property
    def value(self) -> int: ...
    @property
    def tz(self) -> str | None: ...
    def to_numpy(self) -> np.datetime64: ...
    def to_pydatetime(self) -> datetime.datetime: ...
    @property
    def year(self) -> int: ...
    @property
    def month(self) -> int: ...
    @property
    def day(self) -> int: ...
    @property
    def hour(self) -> int: ...
    @property
    def minute(self) -> int: ...
    @property
    def second(self) -> int: ...
    def weekday(self) -> int: ...
    @property
    def microsecond(self) -> int: ...
    @property
    def nanosecond(self) -> int: ...
    @property
    def quarter(self) -> int: ...
    @property
    def dayofweek(self) -> int: ...
    @property
    def day_of_week(self) -> int: ...
    def isoweekday(self) -> int: ...
    @property
    def dayofyear(self) -> int: ...
    @property
    def day_of_year(self) -> int: ...
    @property
    def week(self) -> int: ...
    @property
    def weekofyear(self) -> int: ...
    def isocalendar(self) -> tuple[int, int, int]: ...
    @property
    def days_in_month(self) -> int: ...
    @property
    def daysinmonth(self) -> int: ...
    @property
    def is_month_start(self) -> bool: ...
    @property
    def is_month_end(self) -> bool: ...
    @property
    def is_quarter_start(self) -> bool: ...
    @property
    def is_quarter_end(self) -> bool: ...
    @property
    def is_year_start(self) -> bool: ...
    @property
    def is_year_end(self) -> bool: ...
    @property
    def is_leap_year(self) -> bool: ...
    def day_name(self) -> str: ...
    def month_name(self) -> str: ...
    def date(self) -> datetime.date: ...
    def time(self) -> datetime.time: ...
    def replace(
        self,
        year: int | None = ...,
        month: int | None = ...,
        day: int | None = ...,
        hour: int | None = ...,
        minute: int | None = ...,
        second: int | None = ...,
    ) -> Timestamp: ...
    def floor(self, freq: str) -> Timestamp: ...
    def ceil(self, freq: str) -> Timestamp: ...
    def round(self, freq: str) -> Timestamp: ...
    def normalize(self) -> Timestamp: ...
    def tz_localize(self, tz: Any) -> Timestamp: ...
    def tz_convert(self, tz: Any) -> Timestamp: ...
    def astimezone(self, tz: Any) -> Timestamp: ...
    def utcoffset(self) -> datetime.timedelta | None: ...
    def tzname(self) -> str | None: ...
    def dst(self) -> datetime.timedelta | None: ...
    @property
    def tzinfo(self) -> datetime.tzinfo | None: ...
    def timestamp(self) -> float: ...
    def to_datetime64(self) -> np.datetime64: ...
    def isoformat(self) -> str: ...
    @property
    def unit(self) -> str: ...
    def as_unit(self, unit: str) -> Timestamp: ...
    @staticmethod
    def now(tz: Any | None = ...) -> Timestamp: ...
    @staticmethod
    def today(tz: Any | None = ...) -> Timestamp: ...
    def strftime(self, fmt: str) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: Any, /) -> bool: ...
    def __le__(self, other: Any, /) -> bool: ...
    def __gt__(self, other: Any, /) -> bool: ...
    def __ge__(self, other: Any, /) -> bool: ...
    # Timestamp + timedelta -> Timestamp; Timestamp - Timestamp -> np.timedelta64,
    # Timestamp - timedelta -> Timestamp.
    def __add__(self, delta: Any, /) -> Timestamp: ...
    def __sub__(self, other: Any, /) -> Timestamp | np.timedelta64: ...

# --- Series -----------------------------------------------------------------

@final
class DatetimeAccessor:
    @property
    def year(self) -> Series: ...
    @property
    def month(self) -> Series: ...
    @property
    def day(self) -> Series: ...
    @property
    def hour(self) -> Series: ...
    @property
    def minute(self) -> Series: ...
    @property
    def second(self) -> Series: ...
    @property
    def microsecond(self) -> Series: ...
    @property
    def nanosecond(self) -> Series: ...
    @property
    def dayofweek(self) -> Series: ...
    @property
    def day_of_week(self) -> Series: ...
    @property
    def weekday(self) -> Series: ...
    @property
    def dayofyear(self) -> Series: ...
    @property
    def day_of_year(self) -> Series: ...
    @property
    def quarter(self) -> Series: ...
    @property
    def days_in_month(self) -> Series: ...
    @property
    def daysinmonth(self) -> Series: ...
    @property
    def is_month_start(self) -> Series: ...
    @property
    def is_month_end(self) -> Series: ...
    @property
    def is_quarter_start(self) -> Series: ...
    @property
    def is_quarter_end(self) -> Series: ...
    @property
    def is_year_start(self) -> Series: ...
    @property
    def is_year_end(self) -> Series: ...
    @property
    def is_leap_year(self) -> Series: ...
    @property
    def tz(self) -> str | None: ...
    @property
    def unit(self) -> str: ...
    def day_name(self) -> Series: ...
    def month_name(self) -> Series: ...
    def strftime(self, fmt: str) -> Series: ...
    def normalize(self) -> Series: ...
    def floor(self, freq: str) -> Series: ...
    def ceil(self, freq: str) -> Series: ...
    def round(self, freq: str) -> Series: ...
    def isocalendar(self) -> DataFrame: ...

@final
class Series:
    @staticmethod
    def from_arrow(data: Any, name: str | None = ...) -> Series: ...
    @property
    def name(self) -> str | None: ...
    @property
    def dtype(self) -> str: ...
    @property
    def index(self) -> npt.NDArray[Any]: ...
    @property
    def tz(self) -> str | None: ...
    @property
    def iloc(self) -> SeriesILoc: ...
    @property
    def loc(self) -> SeriesLoc: ...
    @property
    def shape(self) -> tuple[int]: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def to_numpy(self, dtype: str | None = ..., na_value: Any = ...) -> npt.NDArray[Any]: ...
    def __array__(self, dtype: Any = ..., copy: bool | None = ...) -> npt.NDArray[Any]: ...
    def __arrow_c_schema__(self) -> object: ...
    def __arrow_c_array__(self, requested_schema: object | None = ...) -> tuple[object, object]: ...
    def to_arrow(self) -> Any: ...
    def __dlpack__(self, stream: Any = ..., max_version: Any = ..., dl_device: Any = ..., copy: Any = ...) -> Any: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    # Reductions return numpy scalars (pandas' boundary representation): the
    # dtype-preserving ones carry the column's result dtype, the statistics float64.
    def mean(self) -> np.float64: ...
    def sum(self) -> np.float64 | np.int64: ...
    def prod(self) -> np.float64 | np.int64: ...
    def min(self) -> np.float64 | np.int64 | np.bool_ | str | np.datetime64 | NAType: ...
    def max(self) -> np.float64 | np.int64 | np.bool_ | str | np.datetime64 | NAType: ...
    def var(self) -> np.float64: ...
    def std(self) -> np.float64: ...
    def median(self) -> np.float64: ...
    def sem(self) -> np.float64: ...
    def skew(self) -> np.float64: ...
    def kurt(self) -> np.float64: ...
    def corr(self, other: Series) -> float: ...
    def cov(self, other: Series) -> float: ...
    def describe(self) -> Series: ...
    def count(self) -> int: ...
    def nunique(self) -> int: ...
    def unique(self) -> Series: ...
    def sort_values(self, ascending: bool = ..., na_position: str = ...) -> Series: ...
    def head(self, n: int = ...) -> Series: ...
    def tail(self, n: int = ...) -> Series: ...
    def any(self) -> np.bool_: ...
    def all(self) -> np.bool_: ...
    def value_counts(self, normalize: bool = ..., sort: bool = ..., ascending: bool = ..., dropna: bool = ...) -> Series: ...
    def mode(self) -> Series: ...
    def isin(self, values: Any) -> Series: ...
    def between(self, left: float, right: float, inclusive: str = ...) -> Series: ...
    def replace(self, to_replace: Any, value: Any) -> Series: ...
    def nlargest(self, n: int) -> Series: ...
    def nsmallest(self, n: int) -> Series: ...
    def drop_duplicates(self, keep: str = ...) -> Series: ...
    def duplicated(self, keep: str = ...) -> Series: ...
    @property
    def is_monotonic_increasing(self) -> bool: ...
    @property
    def is_monotonic_decreasing(self) -> bool: ...
    @property
    def is_unique(self) -> bool: ...
    def reset_index(self, drop: bool = ...) -> Series | DataFrame: ...
    def sort_index(self, ascending: bool = ...) -> Series: ...
    def rename(self, name: str | None = ...) -> Series: ...
    def copy(self) -> Series: ...
    def to_frame(self, name: str | None = ...) -> DataFrame: ...
    def to_dict(self) -> dict[Any, Any]: ...
    def items(self) -> list[tuple[Any, Any]]: ...
    @property
    def iat(self) -> SeriesILoc: ...
    @property
    def at(self) -> SeriesLoc: ...
    def interpolate(self) -> Series: ...
    def tz_localize(self, tz: str) -> Series: ...
    def tz_convert(self, tz: str) -> Series: ...
    def rolling(self, window: int, min_periods: int | None = ..., center: bool = ...) -> Rolling: ...
    def expanding(self, min_periods: int = ...) -> Expanding: ...
    def ewm(
        self,
        com: float | None = ...,
        span: float | None = ...,
        halflife: float | None = ...,
        alpha: float | None = ...,
        min_periods: int = ...,
        adjust: bool = ...,
        ignore_na: bool = ...,
    ) -> Ewm: ...
    def to_list(self) -> list[Any]: ...
    def shift(self, n: int = ...) -> Series: ...
    def diff(self, n: int = ...) -> Series: ...
    def fillna(self, value: _Scalar, limit: int | None = ...) -> Series: ...
    def ffill(self) -> Series: ...
    def bfill(self) -> Series: ...
    @property
    def dt(self) -> DatetimeAccessor: ...
    def isna(self) -> Series: ...
    def notna(self) -> Series: ...
    def dropna(self) -> Series: ...
    def equals(self, other: Series) -> bool: ...
    def astype(self, dtype: str) -> Series: ...
    def cumsum(self) -> Series: ...
    def cummax(self) -> Series: ...
    def cummin(self) -> Series: ...
    def cumprod(self) -> Series: ...
    def round(self, decimals: int = ...) -> Series: ...
    def rank(self, method: str = ..., ascending: bool = ..., pct: bool = ..., na_option: str = ...) -> Series: ...
    def where(self, cond: Series, other: _Scalar | Series | None = ...) -> Series: ...
    def mask(self, cond: Series, other: _Scalar | Series | None = ...) -> Series: ...
    def abs(self) -> Series: ...
    def clip(self, lower: float | None = ..., upper: float | None = ...) -> Series: ...
    def quantile(self, q: float = ...) -> np.float64: ...
    def idxmax(self) -> _Scalar: ...
    def idxmin(self) -> _Scalar: ...
    # element-wise arithmetic -> Series
    def __add__(self, other: Any, /) -> Series: ...
    def __sub__(self, other: Any, /) -> Series: ...
    def __mul__(self, other: Any, /) -> Series: ...
    def __truediv__(self, other: Any, /) -> Series: ...
    def __radd__(self, other: Any, /) -> Series: ...
    def __rsub__(self, other: Any, /) -> Series: ...
    def __rmul__(self, other: Any, /) -> Series: ...
    def __rtruediv__(self, other: Any, /) -> Series: ...
    def __floordiv__(self, other: Any, /) -> Series: ...
    def __rfloordiv__(self, other: Any, /) -> Series: ...
    # element-wise comparison -> Series. __eq__/__ne__ intentionally widen the object
    # base signature (like pandas / numpy element-wise comparison).
    def __lt__(self, other: Any, /) -> Series: ...
    def __le__(self, other: Any, /) -> Series: ...
    def __eq__(self, other: Any, /) -> Series: ...  # type: ignore[override]
    def __ne__(self, other: Any, /) -> Series: ...  # type: ignore[override]
    def __ge__(self, other: Any, /) -> Series: ...
    def __gt__(self, other: Any, /) -> Series: ...
    # element-wise boolean logic -> Series
    def __and__(self, other: Any, /) -> Series: ...
    def __or__(self, other: Any, /) -> Series: ...
    def __xor__(self, other: Any, /) -> Series: ...
    def __rand__(self, other: Any, /) -> Series: ...
    def __ror__(self, other: Any, /) -> Series: ...
    def __rxor__(self, other: Any, /) -> Series: ...
    def __invert__(self) -> Series: ...
    @overload
    def __getitem__(self, key: _BoolMask, /) -> Series: ...
    @overload
    def __getitem__(self, key: int, /) -> _Scalar: ...
    @overload
    def __getitem__(self, key: slice, /) -> Series: ...
    @overload
    def __getitem__(self, key: str | Timestamp, /) -> _Scalar: ...
    def __setitem__(self, key: _BoolMask | int, value: float | bool, /) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def to_string(
        self,
        na_rep: str = ...,
        float_format: str | None = ...,
        max_rows: int | None = ...,
    ) -> str: ...
    # TA-Lib "Math Transform" group — element-wise, NaN-preserving.
    def acos(self) -> Series: ...
    def asin(self) -> Series: ...
    def atan(self) -> Series: ...
    def ceil(self) -> Series: ...
    def cos(self) -> Series: ...
    def cosh(self) -> Series: ...
    def exp(self) -> Series: ...
    def floor(self) -> Series: ...
    def ln(self) -> Series: ...
    def log10(self) -> Series: ...
    def sin(self) -> Series: ...
    def sinh(self) -> Series: ...
    def sqrt(self) -> Series: ...
    def tan(self) -> Series: ...
    def tanh(self) -> Series: ...

@final
class SeriesILoc:
    @overload
    def __getitem__(self, key: int, /) -> _Scalar: ...
    @overload
    def __getitem__(self, key: slice, /) -> Series: ...

@final
class SeriesLoc:
    @overload
    def __getitem__(self, key: slice, /) -> Series: ...
    @overload
    def __getitem__(self, key: Any, /) -> _Scalar: ...

# --- Row --------------------------------------------------------------------

@final
class Row:
    @property
    def name(self) -> _Scalar: ...
    def __getitem__(self, key: str, /) -> _Scalar: ...
    def to_numpy(self) -> npt.NDArray[np.float64]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def to_string(self) -> str: ...

# --- DataFrame --------------------------------------------------------------

@final
class DataFrame:
    def __new__(
        cls,
        data: dict[str, Any] | DataFrame,
        columns: list[str] | None = ...,
        index: Any | None = ...,
        time_frame: str | TimeFrame | None = ...,
        cumulators: dict[str, Any] | None = ...,
        dtype: str | None = ...,
        window: int | None = ...,
        max_lookback: int | list[str] | None = ...,
    ) -> DataFrame: ...
    @staticmethod
    def from_pandas(pdf: Any) -> DataFrame: ...
    @staticmethod
    def from_arrow(data: Any) -> DataFrame: ...
    @property
    def tz(self) -> str | None: ...
    def tz_localize(self, tz: str) -> DataFrame: ...
    def _set_index_tz(self, tz: str) -> DataFrame: ...
    def tz_convert(self, tz: str) -> DataFrame: ...
    @property
    def columns(self) -> list[str]: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def index(self) -> npt.NDArray[Any]: ...
    @property
    def iloc(self) -> DataFrameILoc: ...
    @property
    def loc(self) -> DataFrameLoc: ...
    @property
    def iat(self) -> DataFrameIat: ...
    @property
    def at(self) -> DataFrameAt: ...
    @property
    def dtypes(self) -> dict[str, str]: ...
    @property
    def ready(self) -> bool: ...
    @property
    def _physical_height(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str, /) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __bool__(self) -> bool: ...
    # Element-wise compare -> bool DataFrame (widens object's base signature, like
    # pandas / the Series operators).
    def __eq__(self, other: Any, /) -> DataFrame: ...  # type: ignore[override]
    def __ne__(self, other: Any, /) -> DataFrame: ...  # type: ignore[override]
    def head(self, n: int = ...) -> DataFrame: ...
    def tail(self, n: int = ...) -> DataFrame: ...
    def count(self) -> Series: ...
    def dropna(self, how: str = ...) -> DataFrame: ...
    def fillna(self, value: _Scalar, limit: int | None = ...) -> DataFrame: ...
    def ffill(self) -> DataFrame: ...
    def bfill(self) -> DataFrame: ...
    def round(self, decimals: int = ...) -> DataFrame: ...
    def cumsum(self) -> DataFrame: ...
    def cummax(self) -> DataFrame: ...
    def cummin(self) -> DataFrame: ...
    def cumprod(self) -> DataFrame: ...
    def abs(self) -> DataFrame: ...
    def clip(self, lower: float | None = ..., upper: float | None = ...) -> DataFrame: ...
    def diff(self, n: int = ...) -> DataFrame: ...
    def shift(self, n: int = ...) -> DataFrame: ...
    def rank(self, method: str = ..., ascending: bool = ..., pct: bool = ..., na_option: str = ...) -> DataFrame: ...
    def sem(self) -> Series: ...
    def skew(self) -> Series: ...
    def kurt(self) -> Series: ...
    def describe(self) -> DataFrame: ...
    def corr(self) -> DataFrame: ...
    def cov(self) -> DataFrame: ...
    def where(self, cond: DataFrame, other: _Scalar | None = ...) -> DataFrame: ...
    def mask(self, cond: DataFrame, other: _Scalar | None = ...) -> DataFrame: ...
    def isna(self) -> DataFrame: ...
    def notna(self) -> DataFrame: ...
    def sort_index(self, ascending: bool = ...) -> DataFrame: ...
    def reset_index(self, drop: bool = ...) -> DataFrame: ...
    def __setitem__(self, key: str | _BoolMask | DataFrame, value: Any, /) -> None: ...
    # column name / directive -> Series; mask / slice / name-list -> sub-frame.
    @overload
    def __getitem__(self, key: str, /) -> Series: ...
    @overload
    def __getitem__(self, key: slice, /) -> DataFrame: ...
    @overload
    def __getitem__(self, key: _BoolMask | list[str], /) -> DataFrame: ...
    def exec(self, directive: str) -> npt.NDArray[Any]: ...
    def get_column(self, key: str) -> Series: ...
    def copy(self) -> DataFrame: ...
    def to_pandas(self, dtype_backend: str = ...) -> Any: ...
    def to_csv(
        self,
        path: str | os.PathLike[str] | None = ...,
        sep: str = ...,
        index: bool = ...,
        header: bool = ...,
        na_rep: str = ...,
        columns: list[str] | None = ...,
        float_format: str | None = ...,
    ) -> str | None: ...
    def sum(self) -> Series: ...
    def prod(self) -> Series: ...
    def mean(self) -> Series: ...
    def var(self) -> Series: ...
    def std(self) -> Series: ...
    def median(self) -> Series: ...
    def quantile(self, q: float = ...) -> Series: ...
    def min(self) -> Series: ...
    def max(self) -> Series: ...
    def nunique(self) -> Series: ...
    def any(self) -> Series: ...
    def all(self) -> Series: ...
    def idxmax(self) -> Series: ...
    def idxmin(self) -> Series: ...
    def isin(self, values: Any) -> DataFrame: ...
    def replace(self, to_replace: Any, value: Any) -> DataFrame: ...
    def nlargest(self, n: int, column: str) -> DataFrame: ...
    def nsmallest(self, n: int, column: str) -> DataFrame: ...
    def drop_duplicates(self, keep: str = ...) -> DataFrame: ...
    def duplicated(self, keep: str = ...) -> Series: ...
    def mode(self) -> DataFrame: ...
    def value_counts(self) -> Series: ...
    def interpolate(self) -> DataFrame: ...
    def rolling(self, window: int, min_periods: int | None = ..., center: bool = ...) -> RollingFrame: ...
    def expanding(self, min_periods: int = ...) -> ExpandingFrame: ...
    def ewm(
        self,
        com: float | None = ...,
        span: float | None = ...,
        halflife: float | None = ...,
        alpha: float | None = ...,
        min_periods: int = ...,
        adjust: bool = ...,
        ignore_na: bool = ...,
    ) -> EwmFrame: ...
    def drop(self, labels: list[Any], axis: int = ..., errors: str = ...) -> DataFrame: ...
    def append(self, other: DataFrame | Row | dict[str, Any]) -> DataFrame: ...
    def to_numpy(self, dtype: str | None = ..., na_value: Any = ...) -> npt.NDArray[Any]: ...
    def fill_into(self, out: npt.NDArray[Any], columns: list[str] | None = ...) -> None: ...
    def __arrow_c_stream__(self, requested_schema: object | None = ...) -> object: ...
    def to_arrow(self) -> Any: ...
    def equals(self, other: DataFrame) -> bool: ...
    def cumulate(self, time_frame: TimeFrame, cumulators: dict[str, Any] | None = ...) -> DataFrame: ...
    def rename(self, columns: dict[str, str]) -> DataFrame: ...
    def set_index(self, keys: str) -> DataFrame: ...
    def astype(self, dtypes: dict[str, str]) -> DataFrame: ...
    def is_computed(self, name: str) -> bool: ...
    def fulfill(self) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def to_string(
        self,
        columns: list[str] | None = ...,
        header: bool = ...,
        index: bool = ...,
        na_rep: str = ...,
        float_format: str | None = ...,
        max_rows: int | None = ...,
        min_rows: int | None = ...,
        show_dimensions: bool = ...,
    ) -> str: ...
    def _repr_html_(self) -> str: ...

@final
class DataFrameILoc:
    @overload
    def __getitem__(self, key: int, /) -> Row: ...
    @overload
    def __getitem__(self, key: slice | list[int] | _BoolMask, /) -> DataFrame: ...
    @overload
    def __getitem__(self, key: tuple[Any, Any], /) -> Any: ...
    def __setitem__(self, key: tuple[Any, Any], value: Any, /) -> None: ...

@final
class DataFrameLoc:
    @overload
    def __getitem__(self, key: slice | _BoolMask, /) -> DataFrame: ...
    @overload
    def __getitem__(self, key: tuple[Any, Any], /) -> Any: ...
    @overload
    def __getitem__(self, key: Any, /) -> Row: ...
    def __setitem__(self, key: tuple[Any, Any], value: Any, /) -> None: ...

@final
class DataFrameIat:
    def __getitem__(self, key: tuple[int, int], /) -> _Scalar: ...
    def __setitem__(self, key: tuple[int, int], value: Any, /) -> None: ...

@final
class DataFrameAt:
    def __getitem__(self, key: tuple[Any, str], /) -> _Scalar: ...
    def __setitem__(self, key: tuple[Any, str], value: Any, /) -> None: ...

# --- TimeFrame --------------------------------------------------------------

@final
class TimeFrame:
    # Preset instances exposed as class attributes (pyo3 ``#[classattr]``): seconds /
    # minutes / hours / days / week / month / year.
    s1: ClassVar[TimeFrame]
    m1: ClassVar[TimeFrame]
    m3: ClassVar[TimeFrame]
    m5: ClassVar[TimeFrame]
    m15: ClassVar[TimeFrame]
    m30: ClassVar[TimeFrame]
    H1: ClassVar[TimeFrame]
    H2: ClassVar[TimeFrame]
    H4: ClassVar[TimeFrame]
    H6: ClassVar[TimeFrame]
    H8: ClassVar[TimeFrame]
    H12: ClassVar[TimeFrame]
    D1: ClassVar[TimeFrame]
    D3: ClassVar[TimeFrame]
    W1: ClassVar[TimeFrame]
    M1: ClassVar[TimeFrame]
    Y1: ClassVar[TimeFrame]
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

# --- module-level functions -------------------------------------------------

def read_csv(
    path: str | os.PathLike[str],
    sep: str | None = ...,
    delimiter: str | None = ...,
    header: bool | None = ...,
    parse_dates: list[str] | None = ...,
    index_col: Any | None = ...,
    na_values: Any | None = ...,
    keep_default_na: bool = ...,
    tz: str | None = ...,
    date_unit: str | None = ...,
) -> DataFrame: ...

def to_datetime(
    obj: Any,
    unit: str = ...,
    format: str | None = ...,
) -> Series: ...

def directive_stringify(directive: str) -> str: ...
def directive_lookback(directive: str) -> int: ...


# Machine-readable audit vocabularies (SPEC §6.3 external anchors): the dtype
# names generated from the Rust DType enum, and the directive command registry.
_dtypes: list[str]
_directive_commands: list[str]

# --- window aggregators ------------------------------------------------------

@final
class Rolling:
    def count(self) -> Series: ...
    def nunique(self) -> Series: ...
    def sum(self) -> Series: ...
    def mean(self) -> Series: ...
    def median(self) -> Series: ...
    def min(self) -> Series: ...
    def max(self) -> Series: ...
    def var(self, ddof: int = ...) -> Series: ...
    def std(self, ddof: int = ...) -> Series: ...
    def sem(self, ddof: int = ...) -> Series: ...
    def skew(self) -> Series: ...
    def kurt(self) -> Series: ...
    def quantile(self, q: float, interpolation: str = ...) -> Series: ...
    def rank(self, method: str = ..., ascending: bool = ..., pct: bool = ...) -> Series: ...
    def first(self) -> Series: ...
    def last(self) -> Series: ...
    def corr(self, other: Series) -> Series: ...
    def cov(self, other: Series, ddof: int = ...) -> Series: ...

@final
class Expanding:
    def count(self) -> Series: ...
    def nunique(self) -> Series: ...
    def sum(self) -> Series: ...
    def mean(self) -> Series: ...
    def median(self) -> Series: ...
    def min(self) -> Series: ...
    def max(self) -> Series: ...
    def var(self, ddof: int = ...) -> Series: ...
    def std(self, ddof: int = ...) -> Series: ...
    def sem(self, ddof: int = ...) -> Series: ...
    def skew(self) -> Series: ...
    def kurt(self) -> Series: ...
    def quantile(self, q: float, interpolation: str = ...) -> Series: ...
    def rank(self, method: str = ..., ascending: bool = ..., pct: bool = ...) -> Series: ...
    def first(self) -> Series: ...
    def last(self) -> Series: ...
    def corr(self, other: Series) -> Series: ...
    def cov(self, other: Series, ddof: int = ...) -> Series: ...

@final
class Ewm:
    def mean(self) -> Series: ...
    def sum(self) -> Series: ...
    def var(self, bias: bool = ...) -> Series: ...
    def std(self, bias: bool = ...) -> Series: ...
    def corr(self, other: Series) -> Series: ...
    def cov(self, other: Series, bias: bool = ...) -> Series: ...

@final
class RollingFrame:
    def count(self) -> DataFrame: ...
    def nunique(self) -> DataFrame: ...
    def sum(self) -> DataFrame: ...
    def mean(self) -> DataFrame: ...
    def median(self) -> DataFrame: ...
    def min(self) -> DataFrame: ...
    def max(self) -> DataFrame: ...
    def var(self, ddof: int = ...) -> DataFrame: ...
    def std(self, ddof: int = ...) -> DataFrame: ...
    def sem(self, ddof: int = ...) -> DataFrame: ...
    def skew(self) -> DataFrame: ...
    def kurt(self) -> DataFrame: ...
    def quantile(self, q: float, interpolation: str = ...) -> DataFrame: ...
    def rank(self, method: str = ..., ascending: bool = ..., pct: bool = ...) -> DataFrame: ...
    def first(self) -> DataFrame: ...
    def last(self) -> DataFrame: ...

@final
class ExpandingFrame:
    def count(self) -> DataFrame: ...
    def nunique(self) -> DataFrame: ...
    def sum(self) -> DataFrame: ...
    def mean(self) -> DataFrame: ...
    def median(self) -> DataFrame: ...
    def min(self) -> DataFrame: ...
    def max(self) -> DataFrame: ...
    def var(self, ddof: int = ...) -> DataFrame: ...
    def std(self, ddof: int = ...) -> DataFrame: ...
    def sem(self, ddof: int = ...) -> DataFrame: ...
    def skew(self) -> DataFrame: ...
    def kurt(self) -> DataFrame: ...
    def quantile(self, q: float, interpolation: str = ...) -> DataFrame: ...
    def rank(self, method: str = ..., ascending: bool = ..., pct: bool = ...) -> DataFrame: ...
    def first(self) -> DataFrame: ...
    def last(self) -> DataFrame: ...

@final
class EwmFrame:
    def mean(self) -> DataFrame: ...
    def sum(self) -> DataFrame: ...
    def var(self, bias: bool = ...) -> DataFrame: ...
    def std(self, bias: bool = ...) -> DataFrame: ...
